spring.application.name: catalogo
server.port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/topicos
          jwk-set-uri: http://keycloak:8080/realms/topicos/protocol/openid-connect/certs

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/catalogo
    username: topicos
    password: topicos
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


  #  cloud.stream:
  #    defaultBinder: rabbit
  #    default.contentType: application/json
  #    bindings.inventory-out-0:
  #      destination: inventory

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        oauth2: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      produtoPreco:
        minimum-number-of-calls: 2
        sliding-window-size: 4
  timelimiter:
    instances:
      produtoPreco:
        timeout-duration: 2s

preco:
  service:
    url: http://localhost:8091/intranet/price/product/

---
spring.config.activate.on-profile: docker
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/topicos
          jwk-set-uri: http://keycloak:8080/realms/topicos/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring.rabbitmq:
  host: message
  port: 5672
  username: guest
  password: guest

preco:
  service:
    url: http://price:8080/intranet/price/product/